name: Daily Sign In

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Run Sign In Script
        env:
          KLW_COOKIE: ${{ secrets.KLW_COOKIE }}
        run: node index.js
